// <auto-generated />
using GraphqlProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphqlProject.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    [Migration("20240116092405_SeedMenusTable")]
    partial class SeedMenusTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphqlProject.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "b",
                            Name = "a",
                            Price = 3m
                        },
                        new
                        {
                            Id = 2,
                            Description = "d",
                            Name = "c",
                            Price = 2m
                        },
                        new
                        {
                            Id = 3,
                            Description = "e",
                            Name = "e",
                            Price = 6m
                        },
                        new
                        {
                            Id = 4,
                            Description = "f",
                            Name = "f",
                            Price = 2m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
